name: deloy-prod

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  tag:
    outputs:
      tag_name: ${{ steps.tag_version.outputs.new_tag }}
      release_name: Release ${{ steps.tag_version.outputs.new_tag }}
      body: ${{ steps.tag_version.outputs.changelog }}
    name: 태그 생성
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  docker:
    name: 도커 이미지 빌드와 푸시
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@v3
      - name: Docker Buildx 설치
        uses: docker/setup-buildx-action@v2
      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: memocode-dev
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 빌드 앤 푸시
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-api-server
          context: .
          push: true
          tags: |
            ghcr.io/memocode-dev/memocode_memo_server:${{ needs.tag.outputs.tag_name }}
            ghcr.io/memocode-dev/memocode_memo_server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  release:
    name: release 생성
    runs-on: ubuntu-latest
    needs: [ docker, tag ]
    steps:
      - uses: actions/checkout@v3
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.tag_name }}
          release_name: ${{ needs.tag.outputs.release_name }}
          body: ${{ needs.tag.outputs.body }}
  deploy:
    runs-on: ubuntu-latest
    needs: [release, tag]
    steps:
      - uses: actions/checkout@v3
      - name: /etc/hosts 업데이트
        run: |
          sudo bash -c "echo '43.202.89.202 prod-server' >> /etc/hosts"
      - name: kubeconfig 세팅
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.MEMOCODE_KUBE_CONFIG }}
      - name: 버전 변경
        run: |
          kubectl set image deployment/prod-memocode-memo-server spring-boot=ghcr.io/memocode-dev/memocode_memo_server:${{ needs.tag.outputs.tag_name }} --namespace=prod